### ISSUE TITLE
Sync with apache/spark/master

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#129]
Notable changes in apache/spark/master post 2.3.0:
* [x] New config key for specifying physical executor cpu requests: https://github.com/apache/spark/pull/20460 (covered in #158).
* [x] Removal of the init-container: https://github.com/apache/spark/pull/20669. Note that this PR also introduced a ConfigMap carrying Spark configuration properties in a file for the driver. The environment variable `SPARK_CONF_DIR` is set to point to the mount path `/opt/spark/conf` of the ConfigMap. This is in conflict with what `spec.sparkConfigMap` is designed to do. Created #216.
* [x] New config key for specifying image pull secrets: https://github.com/apache/spark/pull/20811 (covered in #158).
* [x] Refactoring (internal and won't affect the operator): https://github.com/apache/spark/pull/20910.
* [x] Memory request change (won't affect the operator): https://github.com/apache/spark/pull/20943.
* [x] PySpark support: https://github.com/apache/spark/pull/21092 (the operator should work for PySpark out-of-the-box similarly to what branch spark-2.2-support is) (covered in #181).
* [x] New config mechanism for specifying and mounting volumes: https://github.com/apache/spark/pull/21260 (won't use this as it currently only supports hostPath, emptyDir, and PVC). 
* [x] New config key for specifying secretKeyRef: https://github.com/apache/spark/pull/21317 (covered in #158).
