### ISSUE TITLE
Spark operator roadmap for 2019

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#338]
* [ ] Support for multiple versions of Spark: #182.
* [ ] Support for priority queues and basic priority-based scheduling: #313.
* [ ] Kerberos support that will come in Spark 3.0: #302.
* [ ] `sparkctl` as a `kubectl` plugin: #318.
* [ ] Pod template support that will come in Spark 3.0.

**Comment by skonto** [comment]
I can help with the pod template support, create a poc PR removing the web hook dependency.

**Comment by liyinan926** [comment]
Thanks @skonto. However, we cannot completely get rid of the webhook as it's still needed for Spark prior to 3.0.

**Comment by skonto** [comment]
Maybe we could do breaking changes for new releases no?

**Comment by ChethanUK** [comment]
Is there a new Roadmap? It's like one year now..

**Comment by liyinan926** [comment]
Will create a new one to replace this.
