### ISSUE TITLE
Spark operator roadmap for 2018

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#40]
This is an issue for tracking the 2018 roadmap for the Spark Operator. The list below is tentative and may be constantly updated as ideas and thoughts pop up.

## Features
* [x] Improve `sparkctl`
  * [x] Support uploading application dependencies to GCS (#65).
  * [x] Support uploading application dependencies to S3 (#179).
* [x] Add cron support (#125).
* [x] Add support for mounting user-specified persist volumes (#64).
* [x] Get rid of the initializer (#66).
* [x] Add support for exporting events on `SparkApplication`s to Stackdriver (supported by default on GKE, supported on other providers through the [Stackdriver event exporter](https://github.com/GoogleCloudPlatform/k8s-stackdriver/tree/master/event-exporter)).
* [x] Integration with Prometheus for metrics and monitoring (#67 and #255).
* [ ] Add support for pushing logs grouped by applications to Stackdriver.
* [x] Add Helm Chart for deploying the operator (#79).

## Documentations
* [x] Publish user guide and API definition doc.
* [x] Publish design doc.
* [x] Document v1alpha version of the `SparkApplication` API.

**Comment by foxish** [comment]
I was thinking about a few initial steps to get to the roadmap above. We should solidify the core functionality and get some usage.
That would be good before we try to add more things - since I assume the other things build on top of it.

So, for that I'd add:
- [ ] Support for specifying and supporting all available properties declaratively
- [ ] Support for managing the lifecycle - creating/deleting SparkJobs
- [ ] Basic e2e testing

When we have these, we could do an alpha release and announcement I think - get the word out through a lot of channels.  
I think the missing piece might just be the e2e testing and some discussion around the API.

**Comment by liyinan926** [comment]
Agreed. 1 and 3 are what need to be addressed, particularly e2e testing. I'm gonna take a look at the K8s e2 testing setup.

**Comment by foxish** [comment]
SGTM. Might be worth here to open up a separate tracking issue for first alpha release, v0.1 - so external contributors can tell what we're working towards, and also updating the readme to include goals. I think some common questions like - "is this trying to replace livy" should be clarified to ensure that the community understands what we're building.

**Comment by skonto** [comment]
+Helm chart.
